name: Platform Build

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '39 13 * * *' # run daily

jobs:
  platform_build:
    strategy:
      matrix:
        os: [ rpi3b ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 35 # runtime across all OSs, runs can get queued
    steps:
    - name: Runner Info
      run: printenv | sort

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0' # need full history to get version from git tag

    - name: Install packaged dependencies
      run: .github/install_dependencies

    - name: Configure Build and Test
      run: .github/platform_build ${{ matrix.os }}
